generate_summary:
  dataset_name: ahmed275/opinions_dataset_temporal
  log_file_name: generated_summary_log.log
  login_token: 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
  model: LongT5ForConditionalGeneration.from_pretrained('Stancld/longt5-tglobal-large-16384-pubmed-3k_steps')
  push_dataset_name: ahmed275/generated_summaries_LongT5_tglobal_large
  tokenizer: AutoTokenizer.from_pretrained('Stancld/longt5-tglobal-large-16384-pubmed-3k_steps')
led:
  dataset_name: ahmed275/opinions_dataset_temporal
  log_file_name: t5-large_log.log
  login_token: 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
  model: LongT5ForConditionalGeneration.from_pretrained('Stancld/longt5-tglobal-large-16384-pubmed-3k_steps')
  pretrained_model_save_path: LongT5_tglobal_large/model
  repo_id: ahmed275/LongT5_tglobal_large
  tokenizer: AutoTokenizer.from_pretrained('Stancld/longt5-tglobal-large-16384-pubmed-3k_steps')
